openapi: 3.0.1
info:
  title: Documentación de la App Ecommerce Analogue - Carritos
  description: API para la gestión de carritos de compras en la aplicación.
  version: 1.0.0

paths:
  /api/carts:
    post:
      tags:
        - Carritos
      summary: Crear un nuevo carrito
      description: Crea un nuevo carrito con una lista de productos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      product:
                        type: string
                        description: ID del producto.
                      quantity:
                        type: integer
                        description: Cantidad del producto.
      responses:
        '200':
          description: Carrito creado correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Error interno del servidor.

  /api/carts/{cid}:
    get:
      tags:
        - Carritos
      summary: Obtener un carrito por ID
      description: Recupera un carrito específico por su ID.
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito.
      responses:
        '200':
          description: Carrito obtenido correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Error interno del servidor.

    put:
      tags:
        - Carritos
      summary: Actualizar un carrito
      description: Actualiza los productos en un carrito existente.
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      product:
                        type: string
                        description: ID del producto.
                      quantity:
                        type: integer
                        description: Cantidad del producto.
      responses:
        '200':
          description: Carrito actualizado correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Error interno del servidor.

    delete:
      tags:
        - Carritos
      summary: Vaciar un carrito
      description: Elimina todos los productos de un carrito.
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito.
      responses:
        '200':
          description: Carrito vaciado correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Error interno del servidor.

  /api/carts/{cid}/product/{pid}:
    post:
      tags:
        - Carritos
      summary: Agregar producto al carrito
      description: Agrega un producto específico al carrito.
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito.
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: Cantidad del producto.
      responses:
        '200':
          description: Producto agregado correctamente al carrito.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Error interno del servidor.

    put:
      tags:
        - Carritos
      summary: Actualizar cantidad de producto en el carrito
      description: Actualiza la cantidad de un producto específico en el carrito.
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito.
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: Nueva cantidad del producto.
      responses:
        '200':
          description: Cantidad del producto actualizada correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Error interno del servidor.

    delete:
      tags:
        - Carritos
      summary: Eliminar producto del carrito
      description: Elimina un producto específico del carrito.
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito.
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto.
      responses:
        '200':
          description: Producto eliminado correctamente del carrito.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Error interno del servidor.

  /api/carts/{cid}/purchase:
    post:
      tags:
        - Carritos
      summary: Finalizar compra
      description: Finaliza la compra de todos los productos en el carrito.
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito.
      responses:
        '200':
          description: Compra finalizada correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  ticket:
                    type: object
                    properties:
                      code:
                        type: string
                      purchase_datetime:
                        type: string
                        format: date-time
                      amount:
                        type: number
                      purchaser:
                        type: string
                  notPurchasedProducts:
                    type: array
                    items:
                      type: string
        '500':
          description: Error interno del servidor.

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: object
                properties:
                  _id:
                    type: string
                  title:
                    type: string
                  price:
                    type: number
              quantity:
                type: integer
