openapi: 3.0.1
info:
  title: Documentación de la App Ecommerce Analogue
  description: App especializada en la venta de productos analógicos de diseño
  version: 1.0.0

paths:
  /api/products:
    get:
      tags:
        - Productos
      summary: Obtener todos los productos
      description: Recupera una lista de productos con paginación.
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Número de productos a devolver por página.
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Número de la página a devolver.
        - in: query
          name: sort
          schema:
            type: string
            enum: [asc, desc]
          description: Orden de los productos por precio.
        - in: query
          name: query
          schema:
            type: string
          description: Filtro de búsqueda por categoría.
      responses:
        '200':
          description: Lista de productos obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  totalPages:
                    type: integer
                  prevPage:
                    type: integer
                    nullable: true
                  nextPage:
                    type: integer
                    nullable: true
                  page:
                    type: integer
                  hasPrevPage:
                    type: boolean
                  hasNextPage:
                    type: boolean
                  prevLink:
                    type: string
                    nullable: true
                  nextLink:
                    type: string
                    nullable: true
        '500':
          description: Error del servidor.

    post:
      tags:
        - Productos
      summary: Agregar un nuevo producto
      description: Crea un nuevo producto.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado correctamente.
        '500':
          description: Error del servidor.

  /api/products/{pid}:
    get:
      tags:
        - Productos
      summary: Obtener un producto por ID
      description: Recupera un producto específico por su ID.
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto.
      responses:
        '200':
          description: Producto obtenido correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado.
        '500':
          description: Error del servidor.

    put:
      tags:
        - Productos
      summary: Actualizar un producto
      description: Actualiza los detalles de un producto existente.
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado correctamente.
        '403':
          description: Acceso denegado.
        '404':
          description: Producto no encontrado.
        '500':
          description: Error del servidor.

    delete:
      tags:
        - Productos
      summary: Eliminar un producto
      description: Elimina un producto existente por su ID.
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto.
      responses:
        '200':
          description: Producto eliminado correctamente.
        '403':
          description: Acceso denegado.
        '404':
          description: Producto no encontrado.
        '500':
          description: Error del servidor.

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
        owner:
          type: string
        description:
          type: string
        price:
          type: number
        img:
          type: string
        code:
          type: string
        stock:
          type: number
        category:
          type: string
        status:
          type: boolean
        thumbnails:
          type: array
          items:
            type: string
